### ISSUE TITLE
New release needed ? Or doc update ?

### ISSUE THREAD

**Issue by flohw** [ilovepdf/ilovepdf-php#55]
Hi,

I use the library in my project to ask for signatures. As the documentation states after a task start request, we get the remaining credits only.

I just tested but got a "something went wrong on our side". The response contains "remaining_files" but no trace of "remaining_credits" nor "remaining_pages" as [Task class](https://github.com/ilovepdf/ilovepdf-php/blob/394b496132f755554cbb2650903596c9ec2b8dfc/src/Task.php#L172-L174) references.

Are the credits converted to remaining files properly?

Does it require a library new release with the two new properties (`Task::$remainingPages` and `Task::$remainingCredits`) or the documentation needs an update ? Is the `Task::$remainingFiles` deprecated? It could be nice to add `@deprecated` in this case and mention it on the documentation.

I am a bit worried that the API may change without notice by removing data from response and break in production. Can you provide some information about your upgrade process?

Thank you

**Comment by maztch** [comment]
When user do a start step, api knows the credits cost for the concrete tool, this means it will return remaining pages or remaining files. If you ask to info endpoint, api dones not knows about cost, so response will have remaining credits.
This means for many tools (all previous existing tools), the start will return the same remaining files as before because only new tools are using pages.

**Comment by maztch** [comment]
New iloveapi website with updated documentation is also in process, with currently hidden properties and more endpoints...
